// Code generated by mockery v2.33.0. DO NOT EDIT.

package currencyapi

import mock "github.com/stretchr/testify/mock"

// MockClientOption is an autogenerated mock type for the ClientOption type
type MockClientOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockClientOption) Execute(_a0 *client) {
	_m.Called(_a0)
}

// NewMockClientOption creates a new instance of MockClientOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientOption {
	mock := &MockClientOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
